<template>
  <div>
    <div
      class="splash-background"
      :class="{ 'slide-out-top': view }"
      @click="toggle"
    >
      <img src="/logo/logo-white.png" alt="" class="bounce-in-top logo-image" />
    </div>
    <div v-if="view" class="index-page">
      <div>
        <img src="/banner/main-banner-light.png" class="banner" />
      </div>
      <div class="main-menu-container">
        <img src="/banner/main-sub-logo.png" class="main-menu" alt="" />
      </div>
      <div class="main-card-box">
        <div class="cards" @click="moveSearch">
          <div class="main-card">
            <img src="/maincard/search-button.png" class="card-img" />
            <img src="/maincard/main-move.png" alt="" class="card-img back" />
          </div>
        </div>
        <div class="cards" @click="moveStatistics">
          <div class="main-card">
            <img src="/maincard/statistics-button.png" class="card-img" />
            <img src="/maincard/main-move.png" class="card-img back" />
          </div>
        </div>
      </div>
      <footer-component></footer-component>
    </div>
  </div>
</template>

<script>
export default {
  name: 'IndexPage',
  data() {
    return {
      view: false,
    }
  },
  // created() {
  //   setTimeout(() => {
  //     this.view = true
  //   }, 1200)
  // },
  methods: {
    toggle() {
      this.view = true
    },
    moveSearch() {
      this.$router.push('/search')
    },
    moveStatistics() {
      this.$router.push('/statistics')
    },
  },
}
</script>

<style scoped>
.main-menu-container {
  margin-top: 5vh;
  margin-bottom: 5vh;
  width: 100%;
  display: flex;
  justify-content: center;
}

.main-menu {
  width: 50%;
}
.index-page {
  background-image: url('/background/cloud-background2.svg');
  background-size: cover;
  height: 100%;
}
.back {
  transform: rotateY(180deg);
}
.cards {
  width: 45vw;
  height: 36vh;
  cursor: pointer;
  perspective: 1000px;
}

.main-card-box {
  margin-top: 20px;
  margin-bottom: 10vh;
  padding-bottom: 20px;
  height: 60vh;
  display: flex;
  justify-content: space-around;
  perspective: 1000px;
}
.main-card {
  position: relative;
  transform-style: preserve-3d;
  transform: rotateY(0deg);
  transition: 0.5s;
}

.cards:hover .main-card {
  /* -webkit-animation: flip-scale-down-hor 0.5s linear both;
  animation: flip-scale-down-hor 0.5s linear both; */
  /* -webkit-animation: flip-scale-2-hor-bottom 0.5s linear both;
  animation: flip-scale-2-hor-bottom 0.5s linear both; */
  /* -webkit-animation: flip-scale-up-hor 0.5s linear both;
  animation: flip-scale-up-hor 0.5s linear both; */
  transform: rotateY(-180deg);
}

.card-img {
  width: 45vw;
  height: 50vh;
  position: absolute;
  /* background-color: rgba(125, 214, 255, 0.667); */
  backface-visibility: hidden;
}
.banner {
  width: 100%;
  height: 85vh;
}

::-webkit-scrollbar {
  display: none;
}
.logo-image {
  width: 60%;
  height: 50%;
}

.slide-out-top {
  -webkit-animation: slide-out-top 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53)
    both;
  animation: slide-out-top 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-9-6 13:30:16
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-out-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(-1000px);
    transform: translateY(-1000px);
    opacity: 0;
  }
}
@keyframes slide-out-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(-1000px);
    transform: translateY(-1000px);
    opacity: 0;
  }
}

.bounce-in-top {
  -webkit-animation: bounce-in-top 1.1s both;
  animation: bounce-in-top 1.1s both;
}

.splash-background {
  cursor: pointer;
  position: absolute;
  width: 100%;
  height: 100vh;
  background-image: url('/background/splash-background.svg');
  background-size: cover;
  display: flex;
  justify-content: center;
  align-items: center;
}
@-webkit-keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
    transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
    transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
    transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
@keyframes bounce-in-top {
  0% {
    -webkit-transform: translateY(-500px);
    transform: translateY(-500px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    -webkit-transform: translateY(-65px);
    transform: translateY(-65px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  72% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  81% {
    -webkit-transform: translateY(-28px);
    transform: translateY(-28px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  90% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  95% {
    -webkit-transform: translateY(-8px);
    transform: translateY(-8px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-9-6 18:23:51
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes flip-scale-up-hor {
  0% {
    -webkit-transform: scale(1) rotateX(0);
    transform: scale(1) rotateX(0);
  }
  50% {
    -webkit-transform: scale(2.5) rotateX(-90deg);
    transform: scale(2.5) rotateX(-90deg);
  }
  100% {
    -webkit-transform: scale(1) rotateX(-180deg);
    transform: scale(1) rotateX(-180deg);
  }
}
@keyframes flip-scale-up-hor {
  0% {
    -webkit-transform: scale(1) rotateX(0);
    transform: scale(1) rotateX(0);
  }
  50% {
    -webkit-transform: scale(2.5) rotateX(-90deg);
    transform: scale(2.5) rotateX(-90deg);
  }
  100% {
    -webkit-transform: scale(1) rotateX(-180deg);
    transform: scale(1) rotateX(-180deg);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-9-6 21:10:16
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-scale-down-hor
 * ----------------------------------------
 */
@-webkit-keyframes flip-scale-down-hor {
  0% {
    -webkit-transform: scale(1) rotateX(0);
    transform: scale(1) rotateX(0);
  }
  50% {
    -webkit-transform: scale(0.4) rotateX(90deg);
    transform: scale(0.4) rotateX(90deg);
  }
  100% {
    -webkit-transform: scale(1) rotateX(180deg);
    transform: scale(1) rotateX(180deg);
  }
}
@keyframes flip-scale-down-hor {
  0% {
    -webkit-transform: scale(1) rotateX(0);
    transform: scale(1) rotateX(0);
  }
  50% {
    -webkit-transform: scale(0.4) rotateX(90deg);
    transform: scale(0.4) rotateX(90deg);
  }
  100% {
    -webkit-transform: scale(1) rotateX(180deg);
    transform: scale(1) rotateX(180deg);
  }
}
</style>
